### PR TITLE
add method to use callbacks in json_fields

### PR DESCRIPTION
**Pull request by gucastiliao**
Hello! I was using the lib and it became necessary to modify the data before sending to excel, then I added a method for use of callbacks in json_fields.

If a field need callback, he need to be a object with 2 attributes: 
`field` that is the name of field in `json_data` 
`callback` which receive a function for use with value from `json_data`

Usage example:

```js
json_fields : {
    "Complete name" : "name",
    "City" : "city",
    "Telephone" : {
        field: "phone.landline",
        callback: (value) => {
            return `Landline Phone - ${value}`;
        }
    },
}
```

I believe it is a great option for everyone who also needs to modify the data to send to excel

### CODE REVIEW

**Comment by gusehr** [comment]
Hello @jecovier!

Can you merge this pull request?
I think it is a great and useful feature to the lib.

Hey @gucastiliao 
Thanks for the feature.
If you don't mind, you could add me to your repo, so I can update the docs.
What do you think about it?

Thanks in advance.

**Comment by gucastiliao** [comment]
@gusehr Thank you!
I've added you as a contributor to the repository

**Comment by gusehr** [comment]
OK! Done.

Hello @jecovier 
Can you merge the pr?

Thanks

**Comment by jecovier** [comment]
Hello guys, thanks for this feature!. I see the merge has conflicts, so i'll check it out and test it before publish it.

**Comment by jecovier** [comment]
Thanks a lot @gucastiliao  and @gusehr, this is a great feature! I merged the code and published it.

**Pull request merged**
