### PR TITLE
Addresses issue #72 to give the worksheet tab a name

### PR DESCRIPTION
**Pull request by Per4merKC**
Adds a prop of 'worksheet' to allow the naming of a worksheet tab.  Defaults to "Sheet1"

### CODE REVIEW

**Comment by Davidriquelme** [comment]
@jecovier Hi Javier, is it possible you to merge this ?

**Comment by jecovier** [comment]
@Per4merKC Thank you so much for the commit, sorry for the late merge

**Comment by jecovier** [comment]
@Davidriquelme sorry for the late merge, is ready now

**Comment by Davidriquelme** [comment]
@jecovier gracias!!!!

**Pull request merged**
